config/routes.rb
Rails.application.routes.draw do

  root             'application#home'
  post "/" => "application#home", param: :filter, as: 'home_filtering'

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'search' => 'application#search'
  post 'search' => 'application#search', param: :filter
  delete 'pictures/:id', to: 'pictures#destroy', as: 'destroy_picture'

  resources :users do
    member do
      get :text
      post :subscribe , param: :subscription
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :tags,                only: [:index] do
    delete action: :destroy, on: :member, as: 'un'
    collection do
      post 'tag/:prod_id', action: :create, param: :name, as: 'create'
      get ':name', action: :show, as: 'one_of'
    end
  end

  resources :bookmarks,           only: [:create,:destroy]
  resources :comments, except: [:index, :new] do
    member do
      get 'comment', as: 'reply_on'
      get 'replies', param: :page, as: 'replies_on'
    end
  end

  resources :prods do
    member do
      get 'comments', as: 'comments_on'
    end
  end

  resources :message_groups do
    member do
      post 'talk', as: 'talk_to'
      get 'leave', as: 'leave_the'
      get 'messages', param: :page, as: 'messages_to'
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :author, class_name: "User", foreign_key: "author_id"
  belongs_to :commentable, polymorphic: true
  has_many :replies,  as: :commentable,
                      class_name: "Comment",
                      foreign_key: "commentable_id",
                      inverse_of: :commentable,
                      dependent: :destroy
  has_many :pictures, as: :pictureowner, dependent: :destroy
  default_scope -> { order(:created_at) }
  validates :content, presence: true, length: { maximum: 255 }
  validates :author, presence: true
  scope :created_after, ->(time) { where("created_at >= ?", time) }

  def author_is?(user)
    self.author_id == user.id
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in_user, except: [:show, :replies]
  before_action :on_comment, except: [:new, :create]
  before_action :is_author, only: [:edit, :update]
  before_action :correct_user, only: [:destroy]

  def show
    @current_user = current_user
    id = @comment.id
    comment = @comment
    if comment.commentable_type == "Comment"
      until comment.commentable_type != "Comment" do
        comment = comment.commentable
      end
    end
    case comment.commentable_type
    when "MessageGroup"
      redirect_to message_group_url(comment.commentable_id)+"#comment-#{id}"
    else
      redirect_to comments_on_prod_path(comment.commentable)+"?thread=#{comment.id}#comment-#{id}"
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    if @comment.update(new_comment_params)
      if comment_pics = new_comment_pics[:pics]
        comment_pics.each do |pic|
          @comment.pictures.create!(picture: pic)
        end
        @comment.pictures.reset
      end
    else
      flash[:danger] = "Failed to edit comment"
      #@feed_items = []
      redirect_to url_for(:back) || root_url
    end
    respond_to do |format|
      format.html { redirect_back_or(:root) }
      format.js
    end
  end

  def create
    p = new_comment_params
    @comment = @current_user.comments.build(p)
    @target = case p[:commentable_type]
      when "Prod"
        assosiation = @current_user.discussions
        Prod.find_by(id: p[:commentable_id])
      when "Comment"
        assosiation = @current_user.replies
        Comment.find_by(id: p[:commentable_id])
      when "MessageGroup"
        assosiation = @current_user.messages
        MessageGroup.find_by(id: p[:commentable_id])
      else
        nil
    end
    if @comment.save
      comment_pics = new_comment_pics[:pics]
      comment_pics.each do |pic|
        @comment.pictures.create!(picture: pic)
      end unless comment_pics.nil?
      assosiation.reset
    else
      flash[:danger] = "Failed to post comment"
      #@feed_items = []
      redirect_to url_for(:back) || root_url
    end
    respond_to do |format|
      format.html { redirect_to url_for(@target)+"#comment-#{@comment.id}" }
      format.js
    end
  end

  def destroy
    @comment.destroy
    respond_to do |type|
      type.html { redirect_back_or(:root) }
      type.js { render js: "$('div.comment#comment-#{@comment.id}').remove();" }
    end
  end

  def comment
    @target = @comment
    if @new_comment = @target.replies.build(author: current_user)
      @target.replies.reset
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def replies
    @current_user = current_user
    @target = @comment
    @replies = @target.replies.reload
    per_page = 3
    @max_page = ((@replies.count/per_page.to_f).ceil)-1
    @page = (params[:page]||0).to_i.put_within(0,@max_page)
    @comments = @replies.includes(:pictures, :author)
      .reverse_order
      .offset(@page*per_page)
      .limit(per_page)
      .to_a
      .reverse
    respond_to do |format|
      format.js
      format.html { render layout: "application" }
    end
  end

  private
# ---------- params filtering ---------------------

    def new_comment_params
      params.require(:comment).permit(:content,:commentable_id,:commentable_type)
    end

    def new_comment_pics
      params.require(:comment).permit( {:pics => []} )
    end

# ---------- before_action filters -----------------

    def on_comment
      unless @comment = Comment.includes(:author, :commentable, :pictures).find_by(id: params[:id])
        flash[:danger] = "Comment does not exist."
        redirect_back_or root_url
      end
    end

    def is_author # used after on_comment
      unless @comment.author_is?(@current_user)
        flash[:danger] = "Only author can edit a comment."
        redirect_back_or root_url
      end
    end

    def correct_user # used after on_comment
      unless (( @comment.author_is?(@current_user) ) || @current_user.admin?)
        flash[:danger] = "Only author or admin can delete a comment."
        redirect_back_or root_url
      end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
  
end

app/views/comments/_comment.html.erb
<% commentId="comment-#{comment.id}" %>
<% my = @current_user == comment.author %>
<div class="comment" id="<%= commentId %>" <%= "my" if my %> >
  <a id="comment-<%= comment.id %>"></a>
  <div class="cloud">
    <%= render partial: "users/user_link", locals: {user: comment.author} %>
    <div class="content">
      <% if comment.pictures.any? %>
        <% comment.pictures.each do |pic| %>
          <div class="picture">
            <%= image_tag pic.picture %>
            <% if my %>
              <%= link_to "Delete picture", destroy_picture_url(pic.id), method: :delete, class: "button delete", remote: true %>
            <% end %>
          </div>
        <% end %>
      <% end %>
      <pre><%= sanitize comment.content %></pre>
    </div>
    <div class="actions">
      <div class="timestamp">
        <% if comment.created_at != comment.updated_at %>
        Edited
        <% else %>
        Posted
        <% end %>
        &nbsp; <%= time_ago_in_words(comment.updated_at) %> &nbsp;ago.
      </div>
      <% if @current_user %>
        <% if @current_user.admin? || my %>
          <%= link_to comment_path(comment.id), remote: :true, method: :delete, data: { confirm: "You sure?" } do %>
            <div class="button raised delete">
              Delete
            </div>
          <% end %>
        <% end %>
        <% if @current_user == comment.author %>
          <%= link_to edit_comment_path(id: comment.id),
            id: "edit_comment_#{comment.id}",
            method: :get,
            remote: :true do %>
            <div class="button raised edit">
              Edit
            </div>
          <% end %>
        <% else %>
          <%= link_to reply_on_comment_path(id: comment.id),
            id: "new_comment_on_#{comment.model_name.name}_#{comment.id}",
            method: :get,
            remote: :true do %>
            <div class="button raised add">
              Reply
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="replies" id="replies">
    <% if comment.replies.any? %>
      <% if @thread %>
        <%= render comment.replies %>
      <% else %>
        <%= link_to "Show replies", replies_on_comment_url(comment, page: 0), remote: true unless comment.replies.empty? %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/comments/_comment_form.html.erb
<% case comment.commentable_type %>
  <% when "Comment" %>
    <% type = "Reply" %>
  <% when "Prod" %>
    <% type = "Comment" %>
  <% when "MessageGroup" %>
    <% type = "Send" %>
<% end %>

<div class="comment" id="<%= "comment_on_#{comment.commentable_type}_#{comment.commentable_id}" %>">
  <a id="comment_form"></a>
  <%= form_for comment, remote: true, html: {novalidate: "novalidate"} do |f| %>
    <%= f.hidden_field :commentable_id, :value => comment.commentable_id %>
    <%= f.hidden_field :commentable_type, :value => comment.commentable_type %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="editor previews content raised" id="previews">
      <div class="user">
        <%= render partial: 'users/user_line', locals: {user: comment.author} %>
      </div>
      <%= f.file_field :pics, accept: 'image/jpeg,image/gif,image/png', multiple: true, class: "invisible", onchange: "checkFiles(this)", required: "required" %>
      <%= f.label :pics, class: "button raised add", alt: "Add pictures" do %>
        <%= render file: 'app/assets/images/button-add2.svg' %>
      <% end %>
      <%= f.text_area :content %>
      <%= f.submit type, class: "button save raised" %>
    </div>
  <% end %>
  <script type="text/javascript">
    function checkFiles(input) {
      const MAX_SIZE = 5;
      var previews = input.parentNode;
      Array.prototype.slice.call(previews.querySelectorAll(".preview"))
      .forEach(function(preview){
        delete previews[preview.id];
        previews.removeChild(preview);
      });
      var files = Array.prototype.slice.call(input.files);
      files
      .filter(function(f){ // filter valid
        if (f.size/1024/1024 > MAX_SIZE) {
          previews.dataset.error = "Some files exceed size limit "+MAX_SIZE.toString()+"MB and therefore were ommited";
          return false;
        }
        else {
          delete previews.dataset.error;
          return true;
        }
      })
      .map(function(f){ // create preview elements
        var preview = document.createElement("div");
        var src = URL.createObjectURL(f);
        preview.className = "preview";
        preview.id = f.name;
        preview.dataset.info = f.name+" ["+Math.round(f.size/1024)+"KB]";
        preview.innerHTML = "<img class=\"raised\" src="+src+" />";
        return preview;
      })
      .reduce(function(c,p){ // insert previews at the beginning of previews container
        if (!c[p.id]) {
          c.insertBefore(p,c.children[1]);
          c[p.id] = p;
        }
        return c;
      },previews);
    };
  </script>
</div>

app/views/comments/_replies.html.erb
<% replies.each do |repl| %>
  <%= render partial: 'comments/comment', locals: { comment: repl } %>
<% end %>

app/views/comments/comment.html.erb
<% provide(:title, "Comment over #{@target}") %>
<%= render partial: 'comments/comment_form', locals: {comment: @new_comment} %>
<%= link_to url_for(@target) do %>
  <div class="button delete" style="width: 100%">
    Cancel
  </div>
<% end %>

app/views/comments/comment.js.erb
var c=$("<%= j render partial: 'comments/comment_form', locals: {comment: @new_comment} %>")
, _at = $("#<%= "#{@new_comment.commentable_type.downcase}-#{@new_comment.commentable_id}" %>>#replies");
_at.append(c);
c.append( $("<div class='button delete raised' onclick='javascript: $(this).parent().remove();'><%= j render file: 'app/assets/images/button-destroy.svg' %></div>"));

app/views/comments/create.js.erb
$("div#comment_on_<%= "#{@comment.commentable_type}_#{@comment.commentable_id}" %>")
.<%= @comment.commentable_type == "Comment" ? "replaceWith" : "before" %>(
  $("<%= j render @comment %>"),
)
.find("form#new_comment")[0].reset();
location.href="#<%= "comment-#{@comment.id}" %>";

app/views/comments/edit.html.erb
<% provide(:title, "Edit a comment") %>
<%= render partial: 'comments/comment_form', locals: {comment: @comment} %>

app/views/comments/edit.js.erb
var at = $("div.comment#comment-<%= @comment.id %>");
var cancel_edit_button = $('<div class="button delete raised"><%= j render file: "app/assets/images/button-destroy.svg" %></div>');
at.replaceWith($("<%= j render partial: 'comments/comment_form', locals: {comment: @comment} %>")
.append(cancel_edit_button));
cancel_edit_button.on('click',function(e){
  e.target.parentNode.replaceWith(at[0]);
});

app/views/comments/replies.html.erb
<%= link_to "Show older replies ...", replies_on_comment_url(@target, page: @page+1), remote: true unless (@page+1) > @max_page %>
<%= render @comments %>

app/views/comments/replies.js.erb
$("a[href*=\"<%= request.path %>\"]")
.replaceWith(
  $("<%= link_to "Load more...", replies_on_comment_url(@target, page: @page+1), remote: true unless (@page+1) > @max_page %>\
    <%= j render @comments %>"));

app/views/comments/update.js.erb
$("#comment_on_<%= "#{@comment.commentable_type}_#{@comment.commentable_id}" %>")
.replaceWith($("<%= j render partial: 'comments/comment', locals: { comment: @comment } %>"));
location.href="#";