config/routes.rb
Rails.application.routes.draw do

  root             'application#home'
  post "/" => "application#home", param: :filter, as: 'home_filtering'

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'search' => 'application#search'
  post 'search' => 'application#search', param: :filter
  delete 'pictures/:id', to: 'pictures#destroy', as: 'destroy_picture'

  resources :users do
    member do
      get :text
      post :subscribe , param: :subscription
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :tags,                only: [:index] do
    delete action: :destroy, on: :member, as: 'un'
    collection do
      post 'tag/:prod_id', action: :create, param: :name, as: 'create'
      get ':name', action: :show, as: 'one_of'
    end
  end

  resources :bookmarks,           only: [:create,:destroy]
  resources :comments, except: [:index, :new] do
    member do
      get 'comment', as: 'reply_on'
      get 'replies', param: :page, as: 'replies_on'
    end
  end

  resources :prods do
    member do
      get 'comments', as: 'comments_on'
    end
  end

  resources :message_groups do
    member do
      post 'talk', as: 'talk_to'
      get 'leave', as: 'leave_the'
      get 'messages', param: :page, as: 'messages_to'
    end
  end

end

app/models/prod.rb
class Prod < ActiveRecord::Base
  include PgSearch
  has_many :bookmarks, dependent: :destroy, inverse_of: :prod
  has_many :bookmarked_by, through: :bookmarks, source: :user
  has_many :pictures, as: :pictureowner, dependent: :delete_all
  has_many :comments, as: :commentable, dependent: :delete_all
  has_many :interested, through: :comments, source: :author
  has_many :tags, as: :taggable, dependent: :destroy
  has_many :alike, through: :tags, source: :taggable, source_type: "Prod"
  belongs_to :owner, class_name: "User"
  validates :title, presence: true, length: {maximum: 255}
  validates :owner, presence: true
  validates :description, presence: true, length: {maximum: 4095}
  default_scope -> { order(updated_at: :asc) }
  scope :created_after, ->(time) { where("created_at >= ?", time) }

  pg_search_scope :search, against: [:title, :subtitle, :description],
    associated_against: { tags: :name, owner: :name }

  @@comments_per_page = 3

  def Prod.comments_per_page
    @@comments_per_page
  end

  def bookmarked?(user)
      self.bookmarked_by.include?(user)
  end

  def pictures_attributes=(parameters)
    parameters.each do |pic,action|
      if action["remove_picture"] == "1"
        self.pictures.find(action["id"]).destroy
      end
    end
  end

  def add_pictures=(parameters)
    if !parameters["pictures"].nil?
      parameters["pictures"].each do |pic|
        self.pictures.build(picture: pic)
      end
    end
    if !parameters["remote_picture_url"].empty?
      pic=self.pictures.new
      pic.remote_picture_url=parameters["remote_picture_url"]
      pic.save
    end
  end

  def tojson
    self.as_json(root: true, include: {
      pictures: { root: true },
      bookmarks: { root: true },
      comments: { root: true },
      tags: { root: true }
    }).to_json
  end

  def new_comments_for(time)
    self.comments.created_after(time)
  end
end

app/controllers/prods_controller.rb
class ProdsController < ApplicationController
  before_action :logged_in_user, except: [:show, :index, :comments]
  before_action :list_prods, only: [:show, :comments]
  before_action :set_prod, only: [:edit, :update, :show, :comments]
  before_action :mark_visit, only: [:show, :comments]
  before_action :is_owner, only: [:edit, :update]

  def index
    redirect_to prod_path(id: 1)
  end

  def new
    @prod = @current_user.prods.new(title: "New Gem")
    render 'edit'
  end

  def create
    unsaved_pics = []
    @prod = @current_user.prods.new(prod_parameters)
    if @prod.save
      if @prod_new_pics = prod_pics_params[:add_pictures]
        @prod_new_pics[:pictures].each_with_index do |pic,index|
          p = { picture: pic }
          if @prod_new_pics[:new_params]["#{index}"]
            p[:x] = @prod_new_pics[:new_params]["#{index}"][:x]
            p[:y] = @prod_new_pics[:new_params]["#{index}"][:y]
            p[:scale] = @prod_new_pics[:new_params]["#{index}"][:scale]
          end
          unsaved_pics.push(pic[:filename]) unless @prod.pictures.create!(p)
        end
      end
      if unsaved_pics.length != 0
        flash[:danger] = "Gem successfully saved, but those pictures were not: #{unsaved_pics.join(',')}"
        redirect_to edit_prod(@prod) and return
      end
      flash[:success] = "New prod saved!"
      redirect_to @prod and return
    else
      render 'edit'
    end
  end

  def show
    if @prod.pictures.any?
      if params[:pic].nil?
        @pic = @prod.pictures.first
      else
        @pic = @prod.pictures.find(params[:pic])
      end
    end
    @message_groups = @current_user.chats.reload.includes(:moderator, :conversants, :messages) unless @current_user.nil?
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    unsaved_pics = []
    if @prod.update(prod_parameters)
      if @prod_new_pics = prod_pics_params[:add_pictures]
        @prod_new_pics[:pictures].each_with_index do |pic,index|
          p = { picture: pic }
          if @prod_new_pics[:new_params]["#{index}"]
            p[:x] = @prod_new_pics[:new_params]["#{index}"][:x]
            p[:y] = @prod_new_pics[:new_params]["#{index}"][:y]
            p[:scale] = @prod_new_pics[:new_params]["#{index}"][:scale]
          end
          unsaved_pics.push(pic[:filename]) unless @prod.pictures.create!(p)
        end
      end
      if @prod_pics = prod_pics_params[:pictures_attributes]
        @prod_pics.each do |k,pic|
          newpic = @prod.pictures.find(pic[:id])
          if pic[:remove_picture] == "1"
            newpic.destroy!
          else
            unsaved_pics.push(newpic.picture_identifier) unless newpic.update(pic)
          end
        end
      end
    else
      flash[:danger] = "Failed to save Gem"
      render 'edit' and return
    end
    if unsaved_pics.length > 0
      flash[:danger] = "Failed to save associated pictures: #{unsaved_pics.join(',')}"
      render 'edit' and return
    end
    render 'show'
  end

  def destroy
    if @prod = Prod.find(params[:id] || 1) && @current_user == @prod.owner
      name = @prod.title
      if @prod.destroy
        flash[:success] = "#{name} was successfully removed."
        redirect_to root_url and return
      end
    end
    flash[:danger] = "Gem removal failed."
    redirect_back_or root_url
  end

  def comments
    if page = prod_comments_params[:page]
      per_page = 3
      @max_page = ((@prod.comments.count/per_page.to_f).ceil)-1
      @page = page.to_i.between?(0,@max_page) ? page.to_i : nil
      if !@page.nil?
        @comments = @prod.comments.reverse_order.offset(@page*per_page).limit(per_page).to_a.reverse
      else
        head :no_content and return
      end
    elsif thread = prod_comments_params[:thread]
      if comment = @prod.comments.find_by(id: thread)
        @thread = true
        @comment = comment
        render 'show' and return
      else
        head :no_content and return
      end
    else
      head :no_content and return
    end
    respond_to do |format|
      format.js
      format.html { render "show" }
    end
  end

  private
# ---------- params filtering -------------
    def prod_parameters
      params.require(:prod).permit(
        :title,
        :subtitle,
        :description,
      )
    end

    def prod_comments_params
      params.permit(:page, :thread)
    end

    def prod_pics_params
      params.require(:prod).permit(
        :pictures_attributes => [
          :remove_picture,
          :x,
          :y,
          :scale,
          :id
        ],
        :add_pictures => [
          {:pictures => []},
          :new_params => [
            :x,
            :y,
            :scale
          ]
        ]
      )
    end

# --------------- before_action filters -------------------

    def list_prods
      @prods = Prod.joins(:owner).includes(:pictures, :comments)
    end

    def set_prod
      @prod = Prod.includes(:comments, { :bookmarked_by => [:avatarfile] }, {:tags => [:similar]}, :pictures, :owner).find_by(id: params[:id] || 1)
    end

    def is_owner
      unless @current_user == @prod.owner
        flash[:danger] = "Only owner can edit a gem."
        redirect_back_or @prod
      end
    end


end

app/helpers/prod_helper.rb
module ProdHelper
  
  class HTMLWithPants < Redcarpet::Render::HTML
    include Redcarpet::Render::SmartyPants
  end
  
  def markdown(content)
    @markdown ||= Redcarpet::Markdown.new(HTMLWithPants, {
      autolink: true,
      fenced_code_blocks: true,
      underline: true,
      highlight: true,
      footnotes: true,
      space_after_headers: true
    })
    @markdown.render(content)
  end
end

app/views/prods/_prod.html.erb
<div class="item-row prod-row">
  <div class="item-heading">
    <div class="gem-owner">
      <%= render partial: "users/user_link", locals: { user: prod.owner } %>
    </div>
    <div class="title">
      <%= link_to prod.title, prod_path(prod) %>
    </div>
    <div class="subtitle">
      <%= prod.subtitle %>
    </div>
    <%= render partial: "prods/prod_tags", locals: {prod: prod} %>
  </div>
  <%= render partial: "shared/pictures_collage", locals: { pictures: prod.pictures.limit(4) } %>
  <div class="item-subject">
    <%= link_to prod_path(prod), class: "block" do %>
      <div class="description">
        <%= markdown(prod.description.truncate(250)).html_safe %>
      </div>
    <% end %>
  </div>
</div>

app/views/prods/_prod_bookmarks.html.erb
<div class="bookmarks" id="bookmarked_by">
  <%= render partial: 'bookmarks/bookmark_list', locals: { bookmarkers: @prod.bookmarked_by } %>
  <%= render 'bookmarks/bookmark_form' %>
</div>

app/views/prods/_prod_comments.html.erb
<% num = Prod.comments_per_page %>
<% page = 1 %>
<% if !@page.nil? %>
  <% page = @page+1 %>
  <% num = Prod.comments_per_page*page %>
<% end %>
<div class="comments" id="comments">
  <% if @thread %>
    <%= render @comment %>
  <% else %>
    <%= link_to "Load more comments...", comments_on_prod_url(@prod, page: 1), remote: true unless @prod.comments.count <= num %>
    <%= render @prod.comments.last(num) %>
  <% end %>
  <% if @current_user %>
    <%= render partial: 'comments/comment_form', locals: { comment: @prod.comments.build(author: @current_user) } %>
  <% end %>
  <script type="text/javascript">
    var cb=document.getElementById("messenger-button");
    if (cb) cb.classList.remove("hidden");
    $('a[id^="new_comment_on"], a[id^="edit_comment"]').on('ajax:success',
    function RollbackCommentUrl(){
      history.replaceState({},"<%= "#{@prod.title}" %>","<%= "#{url_for(@prod)}" %>");
    });
  </script>
</div>

app/views/prods/_prod_form.html.erb
<%= stylesheet_link_tag "easymde.min.css", media: "all" %>
<%= javascript_include_tag "easymde.min.js" %>


<section class="gem" id="prod-<%= @prod.id %>">
  <%= form_for @prod, remote: true, html: { multipart: true, class: "gem" } do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= render partial: 'prods/prod_pictures_form', locals: {form: f, prod: @prod} %>
    <div class="gem-page" id="gem-page">
      <%= content_tag :div, class: "title", style: "background-image: url(#{@prod.pictures.first.picture.url})" do %>
         <span class="field" id="title">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </span>
      <% end %>
      <%= content_tag :div, class: "subtitle" do %>
        <span class="field" id="subtitle">
          <%= f.label :subtitle %>
          <%= f.text_field :subtitle, class: "form-control" %>
        </span>
      <% end %>
      <%= content_tag :div, class: "description" do %>
        <span class="editor" id="description">
          <%= f.text_area :description %>
        </span>
      <% end %>
      <%= f.submit "Save", class: "button" %>
      <%= link_to "Cancel", url_for(@prod), class: "button cancel", id: "cancel-prod-edit" %>
    </div>
  <% end %>
  <script type="text/javascript">
    new EasyMDE({element: document.getElementById("prod_description")});
  </script>
</section>

app/views/prods/_prod_list.html.erb
<% if current_prod == nil  then %>
  <% current_prod = @prods[0] %>
<% end %>

<input class="invisible" type=checkbox id="gems-panel-toggle" />
<aside class="gems raised">
  <div class="gems-list" id="gems-list">
    <script type="text/javascript">
      document.getElementById("logo_progress").max=0;
      document.getElementById("logo_progress").value=0;
      function ImgLoad(){
        document.getElementById("logo_progress").value++;
      }
    </script>
    <% @prods.each do |prod| %>
      <%= render partial: 'prods/prod_line', locals: {prod: prod, remote: :true, current: prod.id == current_prod.id ? true : false} %>
    <% end %>
  </div>
</aside>
<script type="text/javascript">
  app.gems = new Rotator((function(){
        var as=document.querySelectorAll(".gems-list a.prod_link");
        var i=as.length;
        var a=new Array(i);
        while (i--){
          a[i] = as[i].href;   // pick a link to a prod;
        }
        return a;
      })());
  document.getElementById("gems-list").scrollTop = document.querySelector(".gems-list .gem-link.current").offsetTop || 0;
</script>

app/views/prods/_prod_pictures.html.erb
<% if !@pic.nil? %>
  <input class="invisible" type=checkbox id="gallery-toggle" />
  <div class="pictures" id="pictures" loaded="true">
    <div class="view scrollable" id="view">
      <%= image_tag @pic.picture.url, class: "imageview", draggable: false,
        id: "imageview",
        "data-src" => "#{@pic.picture.url}",
        "data-id" => "picture-#{@pic.id}",
        "data-x" => "#{@pic.x}",
        "data-y" => "#{@pic.y}",
        "data-scale" => "#{@pic.scale}" %>
    </div>
    <div class="shade" id="shade"></div>
    <div class="button raised hidden" id="zoom-in">+</div>
    <div class="button raised hidden" id="zoom-out">-</div>
    <div class="gallery" id="pictures-view">
      <% @prod.pictures.each do |pic| %>
        <!-- <div class="tile"> -->
          <%= link_to "#{url_for(@prod)}?pic=#{pic.id}", class: "thumbnail" do %>
            <%= image_tag pic.picture.thumb.url, class: "picture",
              id: "picture-#{pic.id}",
              "data-id" => "picture-#{pic.id}",
              "data-src" => "#{pic.picture.url}",
              "data-x" => "#{pic.x}",
              "data-y" => "#{pic.y}",
              "data-scale" => "#{pic.scale}" %>
          <% end %>
        <!-- </div> -->
      <% end %>
    </div>
  </div>
  <script type="text/javascript">
    app.gem.gallery = gallery(document.getElementById("pictures"));
    compileToggles([document.getElementById("gallery-toggle")]);
  </script>
<% else %>
  <div class="pictures" id="pictures" loaded="true">
    <div class="view scrollable" id="view">
      <%= image_tag "assets/prod-picture-placeholder.jpg", class: "imageview" %>
    </div>
  </div>
<% end %>

app/views/prods/_prod_pictures_form.html.erb
<% if @prod.pictures.any? %>
<%   @pic = @prod.pictures.first %>
<% else %>
<%   @pic = @prod.pictures.build %>
<% end %>

<input class="invisible" type=checkbox id="gallery-toggle" />
<div class="pictures" id="pictures" loaded="false">
  <div class="view scrollable" id="view">
    <%= image_tag @pic.picture.url, class: "imageview", draggable: false,
      id: "imageview",
      "data-id" => "picture-#{@pic.id}",
      "data-src" => "#{@pic.picture.url}",
      "data-x" => "#{@pic.x}",
      "data-y" => "#{@pic.y}",
      "data-scale" => "#{@pic.scale}" %>
  </div>
  <div class="shade" id="shade"></div>
  <div class="button raised hidden" id="zoom-in">+</div>
  <div class="button raised hidden" id="zoom-out">-</div>
  <div class="gallery" id="pictures-view">
    <% if @pic.picture.url %>
      <%= form.fields_for :pictures, prod.pictures do |pic| %>
        <% id=pic.object_name.parameterize("_") %>
        <div class="pic-tile">
          <%= pic.hidden_field :id %>
          <%= image_tag pic.object.picture.thumb.url, class: "picture",
            id: id,
            "data-src" => "#{pic.object.picture.url}",
            "data-id" => "#{id}",
            "data-x" => "#{pic.object.x}",
            "data-y" => "#{pic.object.y}",
            "data-scale" => "#{pic.object.scale}" %>
          <%= pic.hidden_field :x %>
          <%= pic.hidden_field :y %>
          <%= pic.hidden_field :scale %>
          <%= pic.check_box :remove_picture, class: "invisible" %>
          <%= pic.label :remove_picture, "x" , class: "button raised delete" %>
        </div>
      <% end %>
    <% end %>
    <%= form.fields_for :add_pictures, prod.pictures.new do |new| %>
      <script type="text/javascript">
        var newname = "<%= j newname=new.object_name %>";
        var newid = "<%= newname.parameterize("_") %>";
      </script>
      <%= new.label :pictures, "+", class: "button raised add" %>
      <%= new.file_field :pictures,
        accept: "image/*",
        multiple: true,
        class: "invisible",
        onchange: "addPic(this)" %>
    <% end %>
  </div>
</div>
<script type="text/javascript">
  app.gem.gallery = gallery(document.getElementById("pictures"));
  function addPic(fileselement){
    var files = fileselement.files;
    var root = fileselement.parentNode;
    var old;
    if (files.length == 0) return;
    $(root).children('input[id^='+newid+'_new_params]').remove();
    for (i in files){
      if (files[i].size <= (5*1024*1024)) {
        var fname = newname+"[new_params]["+i+"]";
        var fid = newid+"_new_params_"+i;
        var image = element("img.picture#"+fid);
        image.setAttribute("loaded",false);
        image.setAttribute("data-id",fid);
        image.setAttribute("data-x","0");
        image.setAttribute("data-y","0");
        image.setAttribute("data-scale","1.0");
        for (d in image.dataset){
          var io = element("input.invisible");
          io.setAttribute("name",fname+"["+d+"]");
          io.id = fid+"_"+d;
          io.setAttribute("value",image.dataset[d]);
          if (old=document.getElementById(io.id)){
            old.parentNode.removeChild(old);
          }
          root.appendChild(io);
        }
        if (old=document.getElementById(fid)){
          old.parentNode.removeChild(old);
        }
        app.gem.gallery["pictures-view"].appendChild(image);
        image.addEventListener("load",function(e){
          this.setAttribute("loaded",true);
        });
        image.src = window.URL.createObjectURL(files[i]);
        image.setAttribute("data-src", image.src);
        app.gem.gallery.pics.push(image);
      }
    }
  }
  compileToggles([document.getElementById("gallery-toggle")]);
</script>

app/views/prods/_prod_tags.html.erb
<div class="tags">
  <% prod.tags.includes({taggable: [:owner]}, :similar).each do |tag| %>
    <%= render partial: 'tags/tag', locals: { tag: tag } %>
  <% end %>
  <%= render partial: 'tags/tag_form', locals: {taggable: prod} if @current_user && (@current_user == prod.owner) %>
</div>

app/views/prods/_prod_tray.html.erb
<ul class="menu" id="tray">
  <li class="menuitem">
    <div class="button raised" id="gems-button">
  		<label for="gems-panel-toggle">
        <img src="<%= asset_path 'gems-icon.png'  %>" />
      </label>
    </div>
  </li>
  <li class="menuitem">
    <div class="button raised" id="gallery-button">
      <label for="gallery-toggle">
        <img src="<%= asset_path 'gallery-icon.png'  %>" />
      </label>
    </div>
  </li>
	<% if logged_in? %>
    <% unread_count = @current_user.unread_messages_count %>
		<% unless !@prod.nil? && (@prod.new_record? || @prod.owner == @current_user) then %>
	    <li class="menuitem">
		      <div class="button raised" id="bookmark-button">
						<label for="new-bookmark">
							<%= render file: 'app/assets/images/button-bookmark.svg' %>
						</label>
		      </div>
	    </li>
		<% end %>
		<li class="menuitem">
			<%= link_to new_prod_url, remote:true do %>
			<div class="button add raised">
				<%= render file: 'app/assets/images/button-add2.svg' %>
			</div>
			<% end %>
		</li>
    <li class="divider"></li>
    <li class="menuitem">
      <label for="messenger-panel-toggle">
        <% if @message_groups.nil? %>
          <%= link_to message_groups_url, id: "messenger-initializer-link", remote: true do %>
          <div class="button raised" id="messenger-button" <%= "counter=#{unread_count}" unless unread_count == 0 %>>
            <%= render file: 'app/assets/images/button-message.svg' %>
          </div>
          <% end %>
        <% else %>
          <div class="button raised" id="messenger-button" <%= "counter=#{unread_count}" unless unread_count == 0 %> >
            <%= render file: 'app/assets/images/button-message.svg' %>
          </div>
        <% end %>
      </label>
    </li>
	<% end %>
</ul>

app/views/prods/comments.js.erb
$("a[href*=\"<%= request.fullpath %>\"]")
.replaceWith(
  $("<%= link_to "Load more...", comments_on_prod_url(@prod, page: @page+1), remote: true unless (@page+1) > @max_page %>\
    <%= j render @comments %>"));

app/views/prods/edit.html.erb
<% provide(:title, @prod.title) %>
<%= render partial: 'prods/prod_form' %>

app/views/prods/edit.js.erb
var title = document.title;
var prod = $("section.gem");
var prodform = $("<%= escape_javascript(render 'prods/prod_form') %>");
// Do
prod.replaceWith(prodform);
document.title = "<%= full_title(@prod.title) %>";
// Undo
prodform.on("click","a#cancel-prod-edit",function(e){
  prodform.replaceWith(prod);
  document.title = title;
  e.preventDefault();
});

app/views/prods/show.html.erb
<% provide(:title, @prod.title) %>

<% if @prod.pictures.any? %>
  <% if @pic.nil? %>
    <% @pic = @prod.pictures.first %>
  <% end %>
  <% facepic = @pic.picture.url %>
<% else %>
  <% facepic = "assets/prod-picture-placeholder.jpg" %>
<% end %>
<section class="gem" id="prod-<%= @prod.id %>">
  <%= render partial: 'prods/prod_list', locals: { current_prod: @prod } unless @prods.nil? %>
  <%= render 'prods/prod_pictures' %>
  <div class="gem-page" id="gem-page">
    <%= render "prods/prod_tray" %>
    <ul class="menu" id="gem-owner">
      <li class="menuitem">
        Published by <%= render partial: "users/user_link", locals: { user: @prod.owner } %>
      </li>
      <% if (!@current_user.nil?) && (@current_user != @prod.owner) %>
        <li class="menuitem">
          <%= render partial: "users/text_user_button", locals: { user: @prod.owner } %>
        </li>
      <% end %>
    </ul>
    <div class="title" style="background-image: url(<%= "#{facepic}" %>)">
      <%= @prod.title %>
      <% if logged_in? %>
        <% if @current_user == @prod.owner %>
          <%= link_to @prod, method: :delete, data: { confirm: "You sure?" } do %>
            <div class="button raised delete">
              Delete
            </div>
          <% end %>
          <%= link_to edit_prod_url(@prod), remote: true do %>
            <div class="button raised edit">
              Edit
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="prod-detail">
      <div class="subtitle">
        <%= @prod.subtitle %>
      </div>
      <div class="description">
        <%= markdown(@prod.description).html_safe %>
      </div>
      <%= render partial: 'prods/prod_tags', locals: {prod: @prod} %>
      <%= render 'prods/prod_bookmarks' %>
      <%= render 'prods/prod_comments' %>
    </div>
  </div>
</section>
<input type=checkbox class="invisible" id="messenger-panel-toggle" />
<section class="messenger-panel">
  <input type="checkbox" class="invisible" name="message-groups-toggle" id="message-groups-toggle">
  <% if !@message_groups.nil? %>
    <%= render "message_groups/messenger" %>
  <% else %>
    <div class="messenger" id="messenger"></div>
  <% end %>
</section>

app/views/prods/show.js.erb
$("section.gem").replaceWith("<%= escape_javascript(render file:'prods/show.html.erb') %>");