config/routes.rb
Rails.application.routes.draw do

  root             'application#home'
  post "/" => "application#home", param: :filter, as: 'home_filtering'

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'search' => 'application#search'
  post 'search' => 'application#search', param: :filter
  delete 'pictures/:id', to: 'pictures#destroy', as: 'destroy_picture'

  resources :users do
    member do
      get :text
      post :subscribe , param: :subscription
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :tags,                only: [:index] do
    delete action: :destroy, on: :member, as: 'un'
    collection do
      post 'tag/:prod_id', action: :create, param: :name, as: 'create'
      get ':name', action: :show, as: 'one_of'
    end
  end

  resources :bookmarks,           only: [:create,:destroy]
  resources :comments, except: [:index, :new] do
    member do
      get 'comment', as: 'reply_on'
      get 'replies', param: :page, as: 'replies_on'
    end
  end

  resources :prods do
    member do
      get 'comments', as: 'comments_on'
    end
  end

  resources :message_groups do
    member do
      post 'talk', as: 'talk_to'
      get 'leave', as: 'leave_the'
      get 'messages', param: :page, as: 'messages_to'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :bookmarks, dependent: :destroy, inverse_of: :user
  has_many :favourites, through: :bookmarks, source: :prod
  has_many :comments, dependent: :destroy, foreign_key: "author_id", inverse_of: :author
  has_many :interests, through: :comments, source: :commentable, source_type: "Prod"
  has_many :prod_comments, -> {where commentable_type: "Prod"},
                    class_name: "Comment",
                    foreign_key: "author_id"
  has_many :replies, -> {where commentable_type: "Comment"},
                    class_name: "Comment",
                    foreign_key: "author_id"
  has_many :messages, -> { where(commentable_type: "MessageGroup").unscope(:order).order(created_at: :desc) },
                    class_name: "Comment",
                    foreign_key: "author_id"
  has_many :conversations, class_name: "MgParticipant", dependent: :destroy
  has_many :chats, through: :conversations, source: :message_group
  has_many :message_groups, dependent: :destroy, foreign_key: "moderator_id", inverse_of: :moderator
  has_many :prods, dependent: :destroy, foreign_key: "owner_id", inverse_of: :owner
  has_one :avatarfile, class_name: "Picture", as: :avatarable, dependent: :destroy
  has_one :subscription, dependent: :destroy

  default_scope -> { where(activated: true).order(last_visit: :asc, updated_at: :asc) }

  attr_accessor :remember_token, :activation_token, :reset_token, :remove_avatar
  before_save   :downcase_email

  has_secure_password

  validates :name, length: {minimum: 6, maximum: 50}
  validates :email, presence: true, if: ':provider == "email"'
  validates :email, length: { maximum: 255 },
    format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }
  validates :provider, presence: true, format: { with: /\A(email|google|facebook)\z/ }
  validates :uid, presence: true
  validates :password, presence: true, length: { minimum: 8,
    too_short: "should have at least 8 characters" },
    format: { with: /(?=.*\d)(?=.*[a-z])(?=.*[A-Z])/,
    message: "should have either a digit, Uppercase and lowercase letter" },
    allow_nil: true

  scope :unactive, -> { unscope(where: :activated).where(activated: false) }

  scope :search, ->(by_name) { where("name ~* ?", ".*#{by_name}.*") }

  @@actions_per_page = 30

  def User.actions_per_page
    @@actions_per_page
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  # def baptize
  #   update_attribute(:admin, true)
  # end

  def authenticated?(token,attribute="remember")
    digest = self.send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def activate
    activation = {activated: true, activated_at: Time.zone.now}
    if self == User.first && !self.admin?
      activation[:admin] = :true
    end
    update_columns(activation)
  end

  def disable
    update_columns(activated: false, activated_at: nil)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, (self.reset_digest = User.digest(reset_token)))
  end

  def create_activation_digest
    self.activation_token  = User.new_token
    update_attribute(:activation_digest, (self.activation_digest = User.digest(activation_token)))
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def bookmark(prod)
    bookmarks.create(prod_id: prod.id)
  end

  def unbookmark(prod)
    bookmarks.find_by(prod_id: prod.id).destroy
  end

  def self.from_omniauth(usr_hash)
    if !(user = User.find_by(provider: usr_hash[:provider], uid: usr_hash[:uid]))
      user = User.create(usr_hash)
      user.password = User.new_token
      user.activated = true
      user.activated_at = Time.zone.now
      user.save!
    end
    user
  end

  def remove_avatar
    update_attribute(:avatar, nil)
    self.avatarfile.destroy if !self.avatarfile(true).nil?
  end

  def feed(scope_names: ["comments","bookmarks"], where_opts: nil, orderby: "updated_at", asc: true, limit: @@actions_per_page, offset: 0)
    sub_query = scope_names.map do |s|
      selection = "id as action_id, \'#{s}\' as action_type, updated_at"
      case s
      when "bookmarks"
        selection += ', prod_id as "on", \'Prod\' as target'
      when "comments"
        selection += ', commentable_id as "on", commentable_type as target'
      else
        return
      end
      self.send("#{s}").select(selection).where(where_opts).unscope(:order).to_sql
    end.join(" UNION ")
    User.connection.select_all("\
      SELECT * \
      FROM (#{sub_query}) as a \
      ORDER BY #{orderby} \
      #{"DESC" unless asc} \
      #{"LIMIT #{limit}" unless limit.nil?} \
      OFFSET #{offset}")
  end

  def following
    User
    .joins(prods: :bookmarks)
    .where("bookmarks.user_id = ? AND users.id != ?", self.id, self.id)
  end

  def discussions
    User
    .joins(prods: :comments)
    .where("comments.author_id = ? AND comments.commentable_type = 'Prod' AND users.id != ?", self.id, self.id)
  end

  def unread_messages_count
    self.conversations.includes({message_group: [:messages]}).map {|c| c.unread.count}.reduce(:+)||0
  end

  def contacts
    if self.admin?
      User.unscope(where: :activated).where.not(id: self.id)
    else
      User
      .joins(prods: [:bookmarks, :comments])
      .where("bookmarks.user_id = ? OR comments.author_id = ?", self.id, self.id)
      .where("users.id != ?", self.id)
      .distinct
    end
  end

  def last_interacted_with(user)
    last_comment = self.comments.select(:updated_at).where(commentable: user.prods.unscope(:order)).unscope(:order).to_sql
    last_like = self.bookmarks.select(:updated_at).where(prod: user.prods.unscope(:order)).unscope(:order).to_sql
    dates = User.connection.select_all("SELECT a.updated_at FROM (#{last_comment} UNION #{last_like}) as a ORDER BY updated_at DESC")
    if dates.any?
      dates[0]["updated_at"]
    else
      DateTime.new(0)
    end
  end

  def notify(grp,name,msg)
    unless self.subscription.nil?
      message = JSON.generate({
        title: "NineLifes/#{name||""}@#{msg.author.name}:",
        body: "#{msg.content}",
        tag:"#{grp}"})
      subscription = self.subscription
      begin
        Webpush.payload_send(
          message: message,
          endpoint: subscription.endpoint,
          p256dh: subscription.key,
          auth: subscription.auth,
          vapid: {
            subject: "mailto:ninelifes@ya64.uk",
            public_key: Rails.application.config.vapidKey.public_key,
            private_key: Rails.application.config.vapidKey.private_key
          }
        )
      rescue
        return
      end
    end
  end

  private
    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token, :only => [:subscribe] # skip csrf token verification from sw-generated requests
  before_action :logged_in_user, except: [:new, :create] # @current_user is set to logged in user
  before_action :on_user,        except: [:new, :create, :index] # @user is set to an existant user, on which an action is about to be performed
  before_action :is_active, except: [:new, :create, :index, :show, :edit]
  before_action :correct_user,   only: [:edit, :update, :destroy]
  before_action :is_me, only: [:subscribe]
  before_action :is_aquainted, only: [:text]

  def new
    @user = User.new
  end

  def index
    @users = @current_user.contacts.includes(:avatarfile, :prods, :comments, :bookmarks)
  end

  def create
    parameters = user_params
    if parameters[:provider] == 'email'
      parameters[:uid] = parameters[:email]
    end
    @user = User.unactive.new(parameters)
    if @user.save
      @user.create_activation_digest
      @user.send_activation_email
      flash[:warning] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    if !@user.activated?
      redirect_to edit_user_path(@user) and return
    end
    @filter = ["comments","bookmarks"]
    @actions_offset = 0
    if filter = user_actions_filter[:actions]
      @activity_filter = case filter
      when "bookmarks"
        @filter = [filter]
        filter.capitalize
      when "comments"
        @filter = [filter]
        filter.capitalize
      else
        nil
      end
    end
    if page = user_actions_filter[:page]
      @page = page.to_i
      @actions_offset = @page*User.actions_per_page
    end
    @user_actions = @user.feed(scope_names: @filter,offset: @actions_offset,asc: false).to_hash
  end

  def edit
    if !@user.activated?
      @user.create_activation_digest
    end
  end

  def update
    if !current_user?(@user) && is_admin_user?
      # admin edits other users profile:
      #   can edit only security params
      security_edit
    else
      # ordinary user or admin edits himself:
      #   can edit name/passwd/avatar
      basic_edit
    end
  end

  def text
    mg = @current_user.message_groups.create(name: @user.name)
    mg.participants.create(user: @user)
    if mg.save
      redirect_to mg
    else
      flash[:danger] = "Failed to create chat"
      redirect_back_or root_url
    end
  end

  def subscribe
    subscription = subscription_params
    if @user.subscription.nil?
      @subscription = @user.build_subscription
    else
      @subscription = @user.subscription
    end
    @subscription.endpoint = subscription[:endpoint]
    @subscription.auth = subscription[:keys][:auth]
    @subscription.key = subscription[:keys][:p256dh]
    @subscription.save
    head :no_content
  end

  def destroy
    if (current_user?(@user) && !@current_user.admin?) || (!current_user?(@user) && @current_user.admin?) # admin cannot delete himself!
      log_out if current_user?(@user)
      name = @user.name
      @user.destroy
      flash[:success] = "User #{name} deleted!"
      redirect_to root_url
    else
      flash[:danger] = "Cannot delete yourself!"
      redirect_back_or @user
    end
  end

  private
# ---------- params filtering ---------------

    def user_params
      params.require(:user).permit(:provider, :uid, :email, :name, :password,
                                   :password_confirmation, :avatar, :remove_avatar)
    end

    def user_params_for_admin
      params.require(:user).permit(:password, :password_confirmation, :activated, :admin)
    end

    def user_actions_filter
      params.permit(:id, :actions, :page)
    end

    def subscription_params
      params.require(:subscription).permit(:endpoint,:expirationTime,:keys => [:p256dh,:auth])
    end

# ----------------- before_action filters ------------------

    def on_user
      from_all_users = if @current_user.admin?
        User.unscope(where: :activated)
      else
        User
      end
      unless @user = from_all_users.includes(:avatarfile, :prods, :favourites).find_by(id: params[:id])
        flash[:danger] = "You need to login to access this page."
        redirect_to login_url
      end
    end

    def is_me
      operation_rejected unless @user == @current_user
    end

    def correct_user
      if !is_admin_user?
        is_me
      end
    end

    def is_active
      unless @user.activated?
        redirect_to root_url and return
      end
    end

    def basic_edit
      parameters = user_params
      if parameters[:remove_avatar] == "1"
        @user.remove_avatar
      end
      if !parameters[:avatar].nil?
        if @user.avatarfile.nil?
          newavatar = @user.build_avatarfile(picture: parameters[:avatar])
          newavatar.picture.resize_to_limit(128,128)
          newavatar.save!
        else
          @user.avatarfile.picture = parameters[:avatar]
          @user.avatarfile(true).picture.resize_to_limit(128,128).save!
        end
        parameters[:avatar] = @user.avatarfile(true).picture_url
      end
      if @user.update_attributes(parameters)
        flash[:success] = "Profile updated"
        redirect_to @user
      else
        flash.now[:danger] = "Provided information doesn't meet requirements."
        render 'edit'
      end
    end

    def security_edit
      parameters = user_params_for_admin
      if parameters.delete(:activated) == "false"
        @user.disable
      end
      if @user.update_attributes(parameters)
        flash[:success] = "Profile updated"
        redirect_to @user
      else
        flash.now[:danger] = "Provided information doesn't meet requirements."
        render 'edit'
      end
    end

    def is_aquainted
      unless @current_user.contacts.include?(@user)
        redirect_to request.referer, flash: { danger: "Cannot text to someone you're not aquainted with.\n You need to bookmark or comment on #{@user.name}'s creations first." }
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper

  def get_avatar_for (user)
    if user.avatarfile.nil?
      if user.avatar.nil?
        default = true
        if !user.email.nil?
          avatar_src = "https://secure.gravatar.com/avatar/#{Digest::MD5::hexdigest(user.email.downcase)}?d=identicon"
        else
          avatar_src = asset_path "nl-icon-96x96.png"
        end
      else
        avatar_src = user.avatar
      end
    else
      avatar_src = user.avatarfile.picture
    end
    image_tag(avatar_src, class: "avatar raised", id: "avatar", alt: "avatar", default: !!(default))
  end
end

app/views/users/_text_user_button.html.erb
<% opts = {class: "button text-user", data: {hint: "Send private message"}} %>
<% if @current_user.nil? %>
  <% url = login_url %>
<% else %>
  <% url = text_user_path(user) %>
<% end %>
<% if (@current_user != user) %>
  <% tag = "a" %>
  <% opts[:href] = url %>
<% else %>
  <% tag = "div" %>
  <% opts[:disabled] = true %>
<% end %>
<%= content_tag tag, opts do %>
  <%= render file: "app/assets/images/button-message.svg" %>
<% end %>

app/views/users/_user.html.erb
<% last_interaction = @current_user.last_interacted_with(user) %>
<div class="item-row user-row" id="user-<%= user.id %>" <%= "unactive" if !user.activated? %>>
  <div class="item-heading">
    <%= render partial: "users/user_profile", locals: { user: user } %>
  </div>
  <%= render partial: "shared/gems_collage", locals: {prods: user.prods.created_after(last_interaction).limit(4)} %>
  <!-- activity -->
  <div class="item-subject">
    <% actions = user.feed(where_opts: ["updated_at > ?", last_interaction], limit: 3, asc: false) %>
    <% if actions.any? %>
      <% actions.each do |user_action| %>
        <%= render partial: "users/user_action", locals: {user_action: user_action} %>
      <% end %>
    <% else %>
      <center>No new actions.</center>
    <% end %>
  </div>
</div>

app/views/users/_user_action.html.erb
<% html_ref="/#{user_action["action_type"]}/#{user_action["action_id"]}" %>

<% if user_action["updated_at"].to_datetime > 1.day.ago %>
  <% timestamp = "on #{user_action["updated_at"].to_datetime.to_formatted_s(:long_ordinal)}" %>
<% else %>
  <% timestamp = "#{time_ago_in_words(user_action["updated_at"].to_datetime)} ago" %>
<% end %>

<p class="user-action" timestamp="<%= timestamp %>">
  <% case user_action["action_type"] %>
    <% when "comments" %>
      <% case user_action["target"] %>
      <% when "Comment" %>
        <%= link_to "Replied", html_ref %> to
        <%= link_to "Comment", controller: user_action["target"].pluralize.downcase, id: user_action["on"], action: :show %>
      <% when "Prod" %>
        <%= link_to "Commented", html_ref %> on
        <%= link_to "Gem", controller: user_action["target"].pluralize.downcase, id: user_action["on"], action: :show %>
      <% when "MessageGroup" %>
        <%= link_to "Texted", html_ref %> to
        <%= link_to "Message group", message_group_url(user_action["on"]) %>
      <% end %>
    <% when "bookmarks" %>
      Bookmarked
      <%= link_to("Gem", { controller: user_action["target"].pluralize.downcase, id: user_action["on"], action: :show }) %>
  <% end %>
  <%= timestamp %>.
</p>

app/views/users/_user_activity_feed.html.erb
<div class="user-actions" id="user-actions">
  <ul class="selector actions-filter">
    <li class="label">
      <div class="icon">
        <%= render file: "app/assets/images/filter.svg" %>
      </div>
    </li>
    <li class="menuitem" <%= "selected" if @activity_filter.nil? %>>
      <%= link_to "All", user_path(@user), remote: true, nav: true %>
    </li>
    <li class="divider"></li>
    <li class="menuitem" <%= "selected" if @activity_filter == "Comments" %>>
      <%= link_to "Comments", user_path(@user, actions: "comments"), remote: true, nav: true %>
    </li>
    <li class="divider"></li>
    <li class="menuitem" <%= "selected" if @activity_filter == "Bookmarks" %>>
      <%= link_to "Bookmarks", user_path(@user, actions: "bookmarks"), remote: true, nav: true %>
    </li>
  </ul>
  <h3><%= @activity_filter || "All activity" %></h3>
  <% if @page && @page > 0 %>
    <div class="button raised page-nav">
      <%= link_to "Previous page ...", user_path(@user, page: @page-1, actions: @activity_filter.nil? ? nil : @activity_filter.downcase), remote: true, nav: true %>
    </div>
  <% end %>
  <% @user_actions.each do |user_action| %>
    <%= render partial: "users/user_action", locals: {user_action: user_action}  %>
  <% end %>
  <% if @user_actions.count == User.actions_per_page %>
    <div class="button raised page-nav">
      <%= link_to "Next page ...", user_path(@user, page: (@page || 0)+1, actions: @activity_filter.nil? ? nil : @activity_filter.downcase), remote: true, nav: true %>
    </div>
  <% end %>
</div>

app/views/users/_user_caption.html.erb
<section class="user_info">
  <h1>
    <%= render partial: 'users/user_link', locals: {user: user} %>
    <%= render partial: 'users/text_user_button', locals: {user: user} %>
  </h1>
  <p>
    <span id="counters">
      <%= pluralize(user.prods.count, "Gem pages") %><br />
      <%= pluralize(user.bookmarks.count, "bookmarks") %><br />
      Comments:<br />
      <ul>
        <li><%= pluralize(user.interests.count, "comments on products") %></li>
        <li><%= pluralize(user.replies.count, "replies on comments") %></li>
      </ul>
    </span>
  </p>
</section>

app/views/users/_user_link.html.erb
<span class="user">
  <%= get_avatar_for(user) %>
  <%= link_to user.name, user %>
</span>

app/views/users/_user_profile.html.erb
<%= render partial: 'users/user_caption', locals: { user: user } %>
<% if current_user.admin? || current_user?(user) %>
  <%= link_to edit_user_url(user) do %>
    <div class="button raised edit">
      Edit profile
    </div>
  <% end %>
<% end %>

app/views/users/_user_select.html.erb
<%= label_tag option_name, class: "user-select" do %>
  <%= check_box_tag option_name, user.id, option_checked ,class: "hidden"%>
  <%= render partial: 'users/user_line', locals: {user: user} %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update <%= current_user?(@user) ? "your" : "#{@user.name}'s" %> profile</h1>

<%= render "users/profileform" %>

app/views/users/index.html.erb
<% provide(:title, "Users") %>
<div class="items-index">
  <%= render @users %>
</div>

app/views/users/index.js.erb
<% provide(:title, "Users") %>
$("body>.items-index").html("<%= j render @users %>");

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<%= render "users/profileform" %>
<%= render "sessions/sociallogin" %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="user-page" id="user-<%= @user.id %>">
  <aside class="user-page-profile">
    <%= render partial: "users/user_profile", locals: { user: @user } %>
  </aside>
  <div class="user-prods">
    <% @user.prods.each do |prod| %>
      <%= render partial: "prods/prod_line", locals: { prod: prod, remote: false, current: false } %>
    <% end %>
  </div>

  <%= render "user_activity_feed" %>
</div>

app/views/users/show.js.erb
$("#user-<%= @user.id %> #user-actions")
.replaceWith($("<%= j render "user_activity_feed" %>"));