config/routes.rb
Rails.application.routes.draw do

  root             'application#home'
  post "/" => "application#home", param: :filter, as: 'home_filtering'

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'search' => 'application#search'
  post 'search' => 'application#search', param: :filter
  delete 'pictures/:id', to: 'pictures#destroy', as: 'destroy_picture'

  resources :users do
    member do
      get :text
      post :subscribe , param: :subscription
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :tags,                only: [:index] do
    delete action: :destroy, on: :member, as: 'un'
    collection do
      post 'tag/:prod_id', action: :create, param: :name, as: 'create'
      get ':name', action: :show, as: 'one_of'
    end
  end

  resources :bookmarks,           only: [:create,:destroy]
  resources :comments, except: [:index, :new] do
    member do
      get 'comment', as: 'reply_on'
      get 'replies', param: :page, as: 'replies_on'
    end
  end

  resources :prods do
    member do
      get 'comments', as: 'comments_on'
    end
  end

  resources :message_groups do
    member do
      post 'talk', as: 'talk_to'
      get 'leave', as: 'leave_the'
      get 'messages', param: :page, as: 'messages_to'
    end
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  
  <nav>
    
  </nav>
</footer>

app/views/layouts/_header.html.erb
<script type="text/javascript">
	var self_url, vapidPublicKey;
</script>
<input type=checkbox class="invisible" id="mainmenu-toggle" />
<ul class="popupmenu raised panel" id="current_session">
  <li class="label" id="logo">
    <label for="mainmenu-toggle">
      <div class="icon logo" id="nls">
				<%= render file: 'app/assets/images/ninelifes-logo.svg' %>
      </div>
      <progress id="logo_progress"></progress>
    </label>
  </li>

	<% if logged_in? %>
	  <% unread_count = @current_user.unread_messages_count %>
	  
    <li class="menuitem">
      <%= link_to message_groups_path do %>
        <div class="button raised" id="messenger-button" <%= "counter=#{unread_count}" unless unread_count == 0 %>>
          <%= render file: 'app/assets/images/button-message.svg' %>
        </div>
      <% end %>
    </li>

	  <input type=checkbox class="invisible" id="user-dropdown" />
		<ul class="menuitem menu dropdown" id="current_user">
		  <li class="label">
		    <label for="user-dropdown">
		      <%= render partial:"users/user_line", locals:{user: @current_user} %>
        </label>
		  </li>
			<li class="menuitem"><label for="user-dropdown"><%= link_to "Profile", current_user %></label></li>
			<li class="divider"></li>
			<li class="menuitem"><label for="user-dropdown"><%= link_to "Log out", logout_path, method: "delete" %></label></li>
		</ul>

		<script type="text/javascript">
			self_url = "<%= subscribe_user_url(@current_user) %>";
			vapidPublicKey = new Uint8Array(<%= Base64.urlsafe_decode64(Rails.application.config.vapidKey.public_key).bytes %>);
		</script>
    
	<% else %>

		<li class="menuitem"><%= link_to "Log in", login_path %></li>
		<li class="menuitem"><%= link_to "Sign up", signup_path %></li>

	<% end %>
  <li class="divider"></li>
  <li class="menuitem">
    <%= link_to "Search", search_path %>
  </li>
  <li class="menuitem">
    <%= link_to "Home", root_path %>
  </li>
</ul>

<% flash.each do |message_type, message| %>
  <%= content_tag :div, class: ["alert", "alert-#{message_type}"] do %>
		<%= message %>
	<% end %>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
  	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="MobileOptimized" content="320"/>
    <meta name="HandheldFriendly" content="true"/>
  	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  	<meta charset="UTF-8" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link rel="manifest" href="/manifest.json" />
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <script>
      const APP_ICON = "<%= asset_path 'nl-icon-96x96.png' %>";
    </script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%=  render "layouts/shim"  %>
  </head>
  <body>
    <header>
      <%=  render "layouts/header"  %>
    </header>
    <%= yield %>
    <!-- <%= debug(params) if Rails.env.development? %> -->
  </body>
</html>